<?php
/** Shared coded template for company, service, visa and destination pages. */
defined('ABSPATH') || exit;

$phone = MM_PHONE_URL;
$email = MM_CONTACT_EMAIL;
$is_archive = is_post_type_archive();
$post_type = $is_archive ? get_query_var('post_type') : get_post_type();
$title = $is_archive ? post_type_archive_title('', false) : get_the_title();
$title = $title ?: 'Visa & Immigration Services';

$type_labels = [
    'mm_service' => 'Service category',
    'mm_visa' => 'Visa guidance',
    'mm_destination' => 'Destination guide',
    'page' => 'Mubeen Migration',
];
$eyebrow = $type_labels[$post_type] ?? 'Mubeen Migration';
$slug = $is_archive ? (string) $post_type : (string) get_post_field('post_name');
$is_visa_page = !$is_archive && in_array($post_type, ['mm_service', 'mm_visa'], true);

$intro = 'Get clear, case-focused international guidance on requirements, documents and the next practical steps for your plans, wherever you are based.';
if ('mm_destination' === $post_type) {
    $intro = 'Explore visa and immigration pathways for ' . $title . ', with practical international direction based on your purpose and circumstances.';
} elseif ('mm_service' === $post_type) {
    $intro = 'Understand the available routes, important eligibility points and evidence commonly required for ' . strtolower($title) . '.';
} elseif ('mm_visa' === $post_type) {
    $intro = 'A clear starting point for understanding the ' . $title . ' route, its evidence requirements, application stages and practical preparation.';
}

$special = [
    'about-us' => ['About Mubeen Migration', 'International immigration guidance built around clarity, careful preparation and responsible advice for individuals, families and businesses.'],
    'contact-us' => ['Contact our team', 'Connect from Pakistan or overseas. Tell us your destination and purpose, and we will identify the most useful next conversation.'],
    'faqs' => ['Frequently asked questions', 'Straightforward answers to common questions about consultations, documents and visa applications.'],
    'work-process' => ['Our work process', 'A structured, transparent process from the first discussion through final preparation.'],
    'privacy-policy' => ['Privacy policy', 'How Mubeen Migration handles the personal information you share with our team.'],
    'immigration' => ['Immigration Services', 'International guidance for temporary visas, permanent residence, family, business and citizenship pathways.'],
    'our-team' => ['Our Team', 'Meet the leadership and consultation team behind Mubeen Migration.'],
    'return-refund' => ['Return & Refund Policy', 'How consultation and professional-service payment requests are reviewed.'],
    'appointment' => ['Book an Appointment', 'Start a focused conversation about your destination and immigration plans.'],
    'blogs' => ['Immigration Insights', 'Practical articles about visas, immigration pathways and responsible application preparation.'],
];
if (isset($special[$slug])) {
    [$title, $intro] = $special[$slug];
}
$page_data = mm_page_content($slug);
if ($page_data) {
    $title = (string) ($page_data['title'] ?? $title);
    $intro = (string) ($page_data['intro'] ?? $intro);
    $eyebrow = (string) ($page_data['eyebrow'] ?? $eyebrow);
}

function mm_site_footer(string $phone, string $email): void {
    mm_render_global_footer($phone, $email);
    return;
    ?>
    <section class="mm-inner-cta"><div class="mm-wrap"><div><span>Start with clarity</span><h2>Discuss your plans with our team.</h2></div><a class="mm-button mm-button-dark" href="<?php echo esc_url($phone); ?>">Call 0321 167 1000</a></div></section>
    <footer class="mm-footer"><div class="mm-wrap"><div class="mm-footer-grid">
        <div class="mm-footer-about"><a class="mm-brand" href="<?php echo esc_url(home_url('/')); ?>"><?php echo mm_brand_logo(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></a><p>International immigration guidance, relevant documentation and careful application preparation for clients in Pakistan and overseas.</p><?php mm_render_social_links(); ?></div>
        <div><h3>Company</h3><a href="<?php echo esc_url(home_url('/about-us/')); ?>">About us</a><a href="<?php echo esc_url(home_url('/work-process/')); ?>">Work process</a><a href="<?php echo esc_url(home_url('/privacy-policy/')); ?>">Privacy policy</a></div>
        <div><h3>Explore</h3><a href="<?php echo esc_url(home_url('/Visa/')); ?>">Visa categories</a><a href="<?php echo esc_url(home_url('/destination/')); ?>">Destinations</a><a href="<?php echo esc_url(home_url('/contact-us/')); ?>">Contact us</a></div>
        <div><h3>Contact</h3><a href="<?php echo esc_url($phone); ?>"><?php echo esc_html(MM_PHONE_DISPLAY); ?></a><a href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($email); ?></a><p>Online consultations worldwide<br>Office: 4th Floor, 51 CCA, DHA Phase 5, Lahore</p></div>
    </div><div class="mm-footer-bottom"><span>&copy; <?php echo esc_html(wp_date('Y')); ?> Mubeen Migration.</span><span>Visa decisions are made by the relevant authorities.</span></div></div></footer>
<?php }
?>
<!doctype html><html <?php language_attributes(); ?>><head><meta charset="<?php bloginfo('charset'); ?>"><meta name="viewport" content="width=device-width, initial-scale=1"><?php wp_head(); ?></head><body <?php body_class('mm-inner-page'); ?>><?php wp_body_open(); ?><a class="mm-skip-link" href="#main-content">Skip to content</a><div class="mm-page">
<?php mm_render_primary_header($phone, $email); ?>
<main id="main-content">
    <section class="mm-inner-hero"><div class="mm-wrap mm-inner-hero-grid"><div><div class="mm-breadcrumb"><a href="<?php echo esc_url(home_url('/')); ?>">Home</a><span>/</span><span><?php echo esc_html($title); ?></span></div><span class="mm-kicker"><?php echo esc_html($eyebrow); ?></span><h1><?php echo esc_html($title); ?></h1><p><?php echo esc_html($intro); ?></p><div class="mm-actions"><a class="mm-button" href="<?php echo esc_url(home_url('/contact-us/#appointment-form')); ?>">Book a consultation</a><a class="mm-button mm-button-outline" href="<?php echo esc_url($phone); ?>">Call our team</a></div></div><figure class="mm-hero-media"><?php mm_render_page_image('mm-hero-image', $title); ?><figcaption>International guidance with organised preparation</figcaption></figure></div></section>
    <?php if ($is_archive && 'mm_service' === $post_type) : ?>
        <section class="mm-inner-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Main Visa categories</span><h2>Choose a Visa category to see its full visa list</h2></div><p>Visa categories group the individual visa-list pages by purpose. Open a category to compare sub visas across destinations.</p></div><div class="mm-visa-main-grid">
            <?php foreach (mm_service_cards() as [$label, $url, $description]) : $service_slug = basename(trim((string) parse_url($url, PHP_URL_PATH), '/')); $count_query = mm_catalog_visa_query(['service' => $service_slug]); ?>
                <article><span><?php echo esc_html((string) $count_query->post_count); ?> visa-list pages</span><h3><?php echo esc_html($label); ?></h3><p><?php echo esc_html($description); ?></p><a href="<?php echo esc_url(home_url($url)); ?>">View sub visa list &rarr;</a></article>
            <?php wp_reset_postdata(); endforeach; ?>
        </div></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Destinations covered</span><h2>Browse Visa categories by country</h2></div><p>Destination pages show the individual visa list for each country in a clearer country-first structure.</p></div><div class="mm-country-list-grid">
            <?php foreach (mm_catalog_countries() as $country_slug => $country_label) : ?><a href="<?php echo esc_url(home_url('/destination/' . $country_slug . '/')); ?>"><strong><?php echo esc_html($country_label); ?></strong><span>View country visa list</span></a><?php endforeach; ?>
        </div></div></section>
    <?php elseif ($is_archive && 'mm_destination' === $post_type) : ?>
        <section class="mm-inner-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Destinations</span><h2>Country-specific visa and immigration pages</h2></div><p>Start with a destination when you already know the country you want to visit, study, work or settle in.</p></div><div class="mm-destination-page-grid">
        <?php if (have_posts()) : while (have_posts()) : the_post(); ?><article><img src="<?php echo esc_url(mm_page_image_url((string) get_post_field('post_name'), (string) get_post_type())); ?>" alt="<?php the_title_attribute(); ?>" loading="lazy"><h3><?php the_title(); ?></h3><p><?php echo esc_html(get_the_excerpt() ?: 'Country-specific visa categories and individual visa-list pages.'); ?></p><a href="<?php the_permalink(); ?>">Open destination &rarr;</a></article><?php endwhile; endif; ?>
        </div></div></section>
    <?php elseif ($is_archive && 'mm_visa' === $post_type) : ?>
        <section class="mm-inner-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Grouped visa directory</span><h2>Find visa pages by country and category</h2></div><p>Use these grouped links for UK, Australia, Canada and US visa categories. The complete visa directory remains available below.</p></div><div class="mm-visa-category-index">
            <?php foreach (mm_nav_visa_groups() as $group => $links) : ?><article><h3><?php echo esc_html($group); ?></h3><?php foreach ($links as [$label, $url]) : ?><a href="<?php echo esc_url(home_url($url)); ?>"><?php echo esc_html($label); ?></a><?php endforeach; ?></article><?php endforeach; ?>
        </div></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Complete visa list</span><h2>All published visa guidance pages</h2></div><p>Browse every available guide, then request an appointment if you need case-specific direction.</p></div><div class="mm-index-grid">
        <?php if (have_posts()) : while (have_posts()) : the_post(); ?><article><img src="<?php echo esc_url(mm_page_image_url((string) get_post_field('post_name'), (string) get_post_type())); ?>" alt="<?php the_title_attribute(); ?>" loading="lazy"><span><?php echo esc_html(str_pad((string) get_the_ID(), 2, '0', STR_PAD_LEFT)); ?></span><h3><?php the_title(); ?></h3><p><?php echo esc_html(get_the_excerpt() ?: 'Requirements, document planning and practical next steps for this visa route.'); ?></p><a href="<?php the_permalink(); ?>">View guidance &rarr;</a></article><?php endwhile; else : ?><p>Guides are being prepared. Please contact our team for assistance.</p><?php endif; ?>
        </div></div></section>
    <?php elseif ($is_archive) : ?>
        <section class="mm-inner-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Explore your options</span><h2>Find the right starting point</h2></div><p>Choose a page below for route-specific information and preparation guidance.</p></div><div class="mm-index-grid">
        <?php if (have_posts()) : while (have_posts()) : the_post(); ?><article><img src="<?php echo esc_url(mm_page_image_url((string) get_post_field('post_name'), (string) get_post_type())); ?>" alt="<?php the_title_attribute(); ?>" loading="lazy"><span><?php echo esc_html(str_pad((string) get_the_ID(), 2, '0', STR_PAD_LEFT)); ?></span><h3><?php the_title(); ?></h3><p><?php echo esc_html(get_the_excerpt() ?: 'Requirements, document planning and practical next steps for this route.'); ?></p><a href="<?php the_permalink(); ?>">View guidance &rarr;</a></article><?php endwhile; else : ?><p>Guides are being prepared. Please contact our team for assistance.</p><?php endif; ?>
        </div></div></section>
    <?php elseif ('mm_service' === $post_type) : ?>
        <?php $service_query = mm_catalog_visa_query(['service' => $slug]); ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-service-layout"><div><span class="mm-kicker">Visa category</span><h2><?php echo esc_html($title); ?> visa-list pages</h2><p>This Visa category collects individual visa-list pages from the UK, United States, Australia and Canada. Use it when you know your purpose, then choose the destination-specific route that fits your plan.</p><div class="mm-service-facts"><div><strong><?php echo esc_html((string) $service_query->post_count); ?></strong><span>Sub visa-list pages</span></div><div><strong>4</strong><span>Main destinations</span></div><div><strong>1-to-1</strong><span>Consultation available</span></div></div></div><figure><?php mm_render_page_image('mm-page-feature-image', $title); ?></figure></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Sub visa list</span><h2>All pages under <?php echo esc_html($title); ?></h2></div><p>Each page includes route-specific guidance, document focus and appointment access.</p></div><div class="mm-visa-list-grid">
            <?php if ($service_query->have_posts()) : while ($service_query->have_posts()) : $service_query->the_post(); $country = (string) get_post_meta(get_the_ID(), '_mm_country_label', true); $group = (string) get_post_meta(get_the_ID(), '_mm_group', true); ?><article><img src="<?php echo esc_url(mm_page_image_url((string) get_post_field('post_name'), 'mm_visa')); ?>" alt="<?php the_title_attribute(); ?>" loading="lazy"><div><span><?php echo esc_html($country ?: 'International'); ?> / <?php echo esc_html($group ?: $title); ?></span><h3><?php the_title(); ?></h3><p><?php echo esc_html(get_the_excerpt()); ?></p><a href="<?php the_permalink(); ?>">Open visa page &rarr;</a></div></article><?php endwhile; wp_reset_postdata(); else : ?><p>No visa-list pages are currently assigned to this category.</p><?php endif; ?>
        </div></div></section>
        <section class="mm-inner-section mm-form-section"><div class="mm-wrap mm-form-layout"><div><span class="mm-kicker">Need help choosing?</span><h2>Discuss <?php echo esc_html($title); ?></h2><p>If you are unsure which sub visa route applies, share your destination and circumstances with our team.</p></div><div><?php mm_render_appointment_form($title); ?></div></div></section>
    <?php elseif ('mm_destination' === $post_type) : ?>
        <?php $country_key = mm_catalog_country_from_destination_slug($slug); $country_label = mm_catalog_country_label($country_key); ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-destination-layout"><figure><?php mm_render_page_image('mm-page-feature-image', $country_label . ' visa guidance'); ?></figure><div><span class="mm-kicker">Destination</span><h2><?php echo esc_html($country_label); ?> visa categories and visa-list pages</h2><p>Use this country page when your destination is clear. The visa-list below is grouped by purpose so you can move from a broad category to the exact page.</p><div class="mm-destination-actions"><?php foreach (mm_service_cards() as [$label, $url]) : ?><a href="#<?php echo esc_attr(basename(trim((string) parse_url($url, PHP_URL_PATH), '/'))); ?>"><?php echo esc_html($label); ?></a><?php endforeach; ?></div></div></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Country visa list</span><h2><?php echo esc_html($country_label); ?> individual visa pages</h2></div><p>Open a visa-list page for clearer content, preparation points and appointment access.</p></div><div class="mm-country-visa-groups">
            <?php foreach (mm_service_cards() as [$label, $url]) : $service_slug = basename(trim((string) parse_url($url, PHP_URL_PATH), '/')); $country_query = mm_catalog_visa_query(['country' => $country_key, 'service' => $service_slug]); if (!$country_query->have_posts()) { wp_reset_postdata(); continue; } ?><section id="<?php echo esc_attr($service_slug); ?>"><h3><?php echo esc_html($label); ?></h3><div class="mm-compact-visa-grid"><?php while ($country_query->have_posts()) : $country_query->the_post(); ?><a href="<?php the_permalink(); ?>"><strong><?php the_title(); ?></strong><span><?php echo esc_html((string) get_post_meta(get_the_ID(), '_mm_group', true)); ?></span></a><?php endwhile; ?></div></section><?php wp_reset_postdata(); endforeach; ?>
        </div></div></section>
        <section class="mm-inner-section mm-form-section"><div class="mm-wrap mm-form-layout"><div><span class="mm-kicker">Destination consultation</span><h2>Plan for <?php echo esc_html($country_label); ?></h2><p>Tell us your goal and we will help identify the most relevant visa category and evidence plan.</p></div><div><?php mm_render_appointment_form($country_label . ' visa consultation'); ?></div></div></section>
    <?php elseif ('mm_visa' === $post_type) : ?>
        <?php $country_label = (string) get_post_meta(get_the_ID(), '_mm_country_label', true); $group = (string) get_post_meta(get_the_ID(), '_mm_group', true); $service_title = (string) get_post_meta(get_the_ID(), '_mm_service_title', true); ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-visa-single-layout"><article><figure class="mm-content-image"><?php mm_render_page_image('mm-page-feature-image', $title); ?></figure><div class="mm-visa-badges"><span><?php echo esc_html($country_label ?: 'International'); ?></span><span><?php echo esc_html($service_title ?: 'Visa guidance'); ?></span><span><?php echo esc_html($group ?: 'Visa list'); ?></span></div><span class="mm-kicker">Visa list page</span><h2><?php echo esc_html($title); ?> guidance</h2><?php if (have_posts()) : while (have_posts()) : the_post(); ?><div class="mm-editor-content"><?php the_content(); ?></div><?php endwhile; endif; ?><div class="mm-visa-info-band"><div><b>Purpose</b><p>Confirm that this visa-list route matches your travel, study, work, family, business or immigration goal.</p></div><div><b>Evidence</b><p>Prepare documents that prove identity, background, funds, sponsor details, employment, study or family links where relevant.</p></div><div><b>Review</b><p>Check forms, dates, previous refusals and declarations for consistency before submission.</p></div></div></article><aside class="mm-side-card"><span>Contact details</span><h2>Discuss this visa</h2><p>Book a case-focused consultation for <?php echo esc_html($title); ?>.</p><a class="mm-button" href="#appointment-form">Request an appointment</a><hr><b><?php echo esc_html(MM_PHONE_DISPLAY); ?></b><small><?php echo esc_html($email); ?></small></aside></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Preparation sections</span><h2>What to review before you apply</h2></div><p>These points are general. Current official requirements and your personal facts must always be checked.</p></div><div class="mm-route-grid"><article><span>Eligibility</span><h3>Route fit</h3><p>Review purpose, allowed activities, sponsor requirements and personal eligibility before preparing documents.</p></article><article><span>Documents</span><h3>Evidence plan</h3><p>Build a focused checklist instead of submitting unrelated or inconsistent information.</p></article><article><span>History</span><h3>Travel and compliance</h3><p>Previous refusals, overstays, gaps or status issues should be reviewed early.</p></article><article><span>Outcome</span><h3>Responsible expectations</h3><p>Visa decisions are made by the relevant authority; preparation improves clarity but cannot guarantee approval.</p></article></div></div></section>
        <section class="mm-inner-section mm-form-section"><div class="mm-wrap mm-form-layout"><div><span class="mm-kicker">Appointment request</span><h2>Ask about <?php echo esc_html($title); ?></h2><p>Submissions are sent to <?php echo esc_html($email); ?> for follow-up.</p></div><div><?php mm_render_appointment_form($title); ?></div></div></section>
    <?php elseif ('about-us' === $slug) : ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-about-page-grid"><figure><?php mm_render_page_image('mm-page-feature-image', 'Mubeen Migration consultation team'); ?><figcaption>Guidance for clients in Pakistan and internationally</figcaption></figure><div><span class="mm-kicker">About our approach</span><h2>Clear immigration guidance, structured around real circumstances.</h2><p>Mubeen Migration supports applicants, families and businesses with route direction, evidence planning and application-readiness reviews. Our work is intentionally practical: understand the goal, identify the correct category, organise evidence and prepare the case consistently.</p><div class="mm-about-metrics"><div><strong>Worldwide</strong><span>Online consultations</span></div><div><strong>Focused</strong><span>Case-by-case planning</span></div><div><strong>Responsible</strong><span>No false guarantees</span></div></div></div></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Why choose us</span><h2>Why clients choose Mubeen Migration</h2></div><p>Every case is different, but dependable preparation follows a clear and accountable structure.</p></div><div class="mm-route-grid"><article><span>01</span><h3>Route clarity</h3><p>We align your destination, genuine purpose and potential visa category before document preparation begins.</p></article><article><span>02</span><h3>Relevant evidence</h3><p>Documents are selected because they support a requirement or explain your circumstances, not simply to add volume.</p></article><article><span>03</span><h3>Transparent communication</h3><p>Requirements, preparation gaps, limitations and practical next steps are explained without false guarantees.</p></article><article><span>04</span><h3>International support</h3><p>Office, phone and online consultations allow us to support clients across Pakistan and overseas.</p></article></div></div></section>
        <section class="mm-inner-section mm-about-purpose"><div class="mm-wrap"><div class="mm-about-mission"><span class="mm-kicker">Our mission</span><h2>Make immigration preparation clearer, more organised and more responsible.</h2><p>Our mission is to help clients understand their options and approach important visa and immigration decisions with accurate information and a structured plan. We aim to reduce avoidable confusion by connecting every form, statement and supporting document to the purpose of the application.</p><p>We measure good service through clarity, responsiveness and preparation quality. Immigration outcomes remain with the relevant authorities, so our responsibility is to provide honest direction and help each client present their circumstances consistently.</p></div><div class="mm-about-values"><span class="mm-kicker">Our values</span><div><article><b>Clarity</b><p>We explain complex requirements and next steps in language clients can understand.</p></article><article><b>Integrity</b><p>We communicate honestly about limitations, risks and decisions outside our control.</p></article><article><b>Care</b><p>We listen to individual circumstances and organise guidance around the real objective.</p></article><article><b>Consistency</b><p>We review forms, dates, history and supporting evidence as one connected application.</p></article></div></div></div></section>
        <?php $ceo_image = mm_media_by_filename('Shahid-Mubeen.jpeg', 'Shahid Mubeen, Chief Executive Officer'); ?>
        <section class="mm-inner-section mm-leader-section"><div class="mm-wrap mm-leader-grid"><figure><img src="<?php echo esc_url($ceo_image['url']); ?>" alt="<?php echo esc_attr($ceo_image['alt'] ?: 'Shahid Mubeen, Chief Executive Officer'); ?>" loading="lazy"></figure><div><span class="mm-kicker">Leadership</span><h2>Shahid Mubeen</h2><h3>Chief Executive Officer</h3><p>Shahid Mubeen leads Mubeen Migration with a client-first approach centred on route clarity, careful document planning and realistic expectations. His focus is to make complex immigration processes easier to understand while maintaining responsible standards at every stage.</p><a class="mm-text-link" href="<?php echo esc_url(home_url('/our-team/')); ?>">Meet our team &rarr;</a></div></div></section>
    <?php elseif ('immigration' === $slug) : ?>
        <section class="mm-inner-section mm-immigration-overview"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Pathways by objective</span><h2>Build the plan around your real immigration goal</h2></div><p>Start with purpose and destination, then compare eligibility, evidence and longer-term implications.</p></div><div class="mm-immigration-grid"><?php foreach (($page_data['sections'] ?? []) as $index => $section) : ?><article><b><?php echo esc_html(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)); ?></b><h3><?php echo esc_html((string) $section['title']); ?></h3><p><?php echo esc_html((string) $section['text']); ?></p></article><?php endforeach; ?></div></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap mm-immigration-split"><div><span class="mm-kicker">A connected strategy</span><h2>Temporary and permanent plans need different evidence.</h2><p>A short visit, degree programme, sponsored role, family application and permanent residence pathway each require a different legal purpose and supporting record. We help organise the questions before documents are collected.</p><ul><li>Destination and route comparison</li><li>Eligibility and risk discussion</li><li>Evidence and document planning</li><li>Application-readiness review</li></ul></div><div class="mm-gold-panel"><span>Explore by destination</span><h3>Country-specific options</h3><?php foreach (mm_nav_destination_links() as [$label, $url]) : ?><a href="<?php echo esc_url(home_url($url)); ?>"><?php echo esc_html($label); ?> <span>&rarr;</span></a><?php endforeach; ?></div></div></section>
    <?php elseif ('our-team' === $slug) : ?>
        <?php $leader = $page_data['leader'] ?? []; $leader_image = mm_media_by_filename((string) ($leader['image'] ?? 'Shahid-Mubeen.jpeg'), 'Shahid Mubeen, Chief Executive Officer'); ?>
        <section class="mm-inner-section mm-team-lead"><div class="mm-wrap mm-team-lead-grid"><figure><img src="<?php echo esc_url($leader_image['url']); ?>" alt="<?php echo esc_attr($leader_image['alt'] ?: 'Shahid Mubeen, Chief Executive Officer'); ?>" loading="lazy"><figcaption>Leadership grounded in responsible client service</figcaption></figure><div><span class="mm-kicker">Chief Executive Officer</span><h2><?php echo esc_html((string) ($leader['name'] ?? 'Shahid Mubeen')); ?></h2><h3><?php echo esc_html((string) ($leader['role'] ?? 'Chief Executive Officer')); ?></h3><p><?php echo esc_html((string) ($leader['bio'] ?? '')); ?></p><blockquote>Clear direction comes before document preparation.</blockquote></div></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">How the team works</span><h2>One service standard across every client conversation</h2></div><p>Our consultants and support team organise each enquiry around clarity, preparation and responsible expectations.</p></div><div class="mm-team-values"><?php foreach (($page_data['values'] ?? []) as $value) : ?><article><h3><?php echo esc_html((string) $value['title']); ?></h3><p><?php echo esc_html((string) $value['text']); ?></p></article><?php endforeach; ?></div></div></section>
    <?php elseif ('return-refund' === $slug) : ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-policy-layout"><aside><span class="mm-kicker">At a glance</span><h2>Requests are reviewed against the service delivered.</h2><p>Immigration professional services are time-based and often begin before a final application is submitted. Keep invoices, engagement terms and correspondence for reference.</p><a href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($email); ?></a></aside><article><?php foreach (($page_data['sections'] ?? []) as $index => $section) : ?><section><span><?php echo esc_html(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)); ?></span><div><h2><?php echo esc_html((string) $section['title']); ?></h2><p><?php echo esc_html((string) $section['text']); ?></p></div></section><?php endforeach; ?><small>Last reviewed: <?php echo esc_html(wp_date('F Y')); ?>. Any signed service agreement takes priority where its terms differ.</small></article></div></section>
    <?php elseif ('appointment' === $slug) : ?>
        <section class="mm-inner-section mm-appointment-intro"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Before the consultation</span><h2>Three steps to a more useful first conversation</h2></div><p>You do not need every document ready, but accurate background information helps us understand the route.</p></div><div class="mm-appointment-steps"><?php foreach (($page_data['steps'] ?? []) as $index => $step) : ?><article><b><?php echo esc_html((string) ($index + 1)); ?></b><h3><?php echo esc_html((string) $step['title']); ?></h3><p><?php echo esc_html((string) $step['text']); ?></p></article><?php endforeach; ?></div></div></section>
        <section class="mm-inner-section mm-form-section"><div class="mm-wrap mm-form-layout"><div><span class="mm-kicker">Appointment request</span><h2>Tell us what you want to achieve</h2><p>Your form is sent to <?php echo esc_html($email); ?>. Consultation availability and any applicable fee will be confirmed during follow-up.</p><div class="mm-contact-list"><a href="<?php echo esc_url($phone); ?>"><b>Phone / WhatsApp</b><span><?php echo esc_html(MM_PHONE_DISPLAY); ?></span></a><div><b>International clients</b><span>Online and telephone appointments available</span></div></div></div><div><?php mm_render_appointment_form('Immigration consultation'); ?></div></div></section>
    <?php elseif ('blogs' === $slug) : ?>
        <?php $blog_query = new WP_Query(['post_type' => 'post', 'post_status' => 'publish', 'posts_per_page' => 12, 'paged' => max(1, (int) get_query_var('paged'))]); ?>
        <section class="mm-inner-section mm-blog-index"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">Latest articles</span><h2>Practical immigration reading</h2></div><p>General information to help you ask better questions and prepare more carefully. Always confirm current official requirements.</p></div><?php if ($blog_query->have_posts()) : ?><div class="mm-blog-grid"><?php while ($blog_query->have_posts()) : $blog_query->the_post(); ?><article><a class="mm-blog-image" href="<?php the_permalink(); ?>"><?php if (has_post_thumbnail()) : the_post_thumbnail('large', ['loading' => 'lazy']); else : ?><img src="<?php echo esc_url(mm_page_image_url((string) get_post_field('post_name'), 'post')); ?>" alt="<?php the_title_attribute(); ?>" loading="lazy"><?php endif; ?></a><div><span><?php echo esc_html(get_the_date()); ?></span><h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2><p><?php echo esc_html(get_the_excerpt() ?: wp_trim_words(wp_strip_all_tags(get_the_content()), 24)); ?></p><a class="mm-text-link" href="<?php the_permalink(); ?>">Read article &rarr;</a></div></article><?php endwhile; ?></div><?php else : ?><div class="mm-empty-state"><h2>New immigration articles are being prepared.</h2><p>In the meantime, explore our visa categories or book a consultation for case-specific direction.</p><a class="mm-button mm-button-dark" href="<?php echo esc_url(home_url('/Visa/')); ?>">Explore visa categories</a></div><?php endif; wp_reset_postdata(); ?></div></section>
    <?php elseif ('work-process' === $slug) : ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-process-page"><div class="mm-section-heading"><div><span class="mm-kicker">Work process</span><h2>From first conversation to submission readiness</h2></div><p>A clear workflow keeps requirements, timelines and evidence gaps visible.</p></div><div class="mm-process-timeline"><?php foreach ([['Initial consultation','We discuss your destination, purpose, history and urgent concerns.'],['Route and eligibility review','We identify the most relevant visa/service category and key risks.'],['Document checklist','You receive focused document direction based on your circumstances.'],['Application preparation','Forms, evidence and explanations are organised for consistency.'],['Final readiness review','The case is checked before submission or next action.']] as $index => $step) : ?><article><b><?php echo esc_html(str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT)); ?></b><div><h3><?php echo esc_html($step[0]); ?></h3><p><?php echo esc_html($step[1]); ?></p></div></article><?php endforeach; ?></div></div></section>
        <section class="mm-inner-section mm-form-section"><div class="mm-wrap mm-process-visual-grid"><figure><?php mm_render_page_image('mm-page-feature-image', 'Visa work process'); ?></figure><div><span class="mm-kicker">Prepared, not rushed</span><h2>Each stage has a purpose.</h2><p>We keep communication direct and practical so you understand what is needed, why it matters and how it fits into the application route.</p><a class="mm-button mm-button-dark" href="<?php echo esc_url(home_url('/contact-us/#appointment-form')); ?>">Start with an appointment</a></div></div></section>
    <?php elseif ('contact-us' === $slug) : ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-contact-grid"><div><span class="mm-kicker">Get in touch</span><h2>Speak with a consultant</h2><p>We work with clients in Pakistan and overseas through office, phone and online consultations. For an efficient first discussion, share your intended country, purpose of travel and any previous visa history.</p><div class="mm-contact-list"><a href="<?php echo esc_url($phone); ?>"><b>Phone / WhatsApp</b><span><?php echo esc_html(MM_PHONE_DISPLAY); ?></span></a><a href="mailto:<?php echo esc_attr($email); ?>"><b>Email</b><span><?php echo esc_html($email); ?></span></a><div><b>Consultations</b><span>Available internationally by phone or online</span></div><div><b>Office</b><span>4th Floor, 51 CCA, DHA Phase 5, Lahore 54000</span></div></div></div><div class="mm-gold-panel"><span>Consultation checklist</span><h3>What to bring</h3><ul><li>Passport and travel history</li><li>Education or employment details</li><li>Previous refusal letters, if any</li><li>Your destination and intended purpose</li></ul></div></div></section>
        <section class="mm-contact-map-section"><div class="mm-wrap mm-contact-map-grid"><div><span class="mm-kicker">Visit our office</span><h2>Find Mubeen Migration in DHA Phase 5</h2><p>4th Floor, 51 CCA, DHA Phase 5, Lahore 54000, Pakistan.</p><a class="mm-text-link" href="https://www.google.com/maps/search/?api=1&amp;query=4th+Floor%2C+51+CCA%2C+DHA+Phase+5%2C+Lahore+54000%2C+Pakistan" target="_blank" rel="noopener noreferrer">Open directions in Google Maps &rarr;</a></div><div class="mm-map-frame"><iframe title="Google Map showing Mubeen Migration office at 51 CCA, DHA Phase 5, Lahore" src="https://www.google.com/maps?q=4th%20Floor%2C%2051%20CCA%2C%20DHA%20Phase%205%2C%20Lahore%2054000%2C%20Pakistan&amp;output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe></div></div></section>
        <section class="mm-inner-section mm-form-section"><div class="mm-wrap mm-form-layout"><div><span class="mm-kicker">Book an appointment</span><h2>Tell us about your plans</h2><p>Complete the form and your enquiry will be sent directly to our consultation team at <?php echo esc_html($email); ?>.</p></div><div><?php mm_render_appointment_form('General consultation'); ?></div></div></section>
    <?php elseif ('faqs' === $slug && !empty($page_data['items'])) : ?>
        <section class="mm-inner-section mm-faq-page"><div class="mm-wrap mm-faq-grid"><div class="mm-faq-intro"><span class="mm-kicker">Questions clients ask</span><h2>Clear answers support better decisions</h2><p>These answers are general information. The correct route and evidence depend on your destination and personal circumstances.</p><a class="mm-button mm-button-dark" href="<?php echo esc_url(home_url('/appointment/')); ?>">Ask about your case</a></div><div class="mm-accordion"><?php foreach ($page_data['items'] as $i => $faq) : ?><details<?php echo 0 === $i ? ' open' : ''; ?>><summary><?php echo esc_html((string) $faq['question']); ?></summary><p><?php echo esc_html((string) $faq['answer']); ?></p></details><?php endforeach; ?></div></div></section>
        <section class="mm-inner-section mm-route-section"><div class="mm-wrap mm-faq-contact"><div><span class="mm-kicker">Still need direction?</span><h2>General answers cannot replace a case review.</h2><p>Book a consultation when your question depends on travel history, finances, sponsorship, previous refusals or immigration status.</p></div><div><a href="<?php echo esc_url($phone); ?>"><?php echo esc_html(MM_PHONE_DISPLAY); ?></a><a href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($email); ?></a></div></div></section>
    <?php elseif ('faqs' === $slug) : ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-faq-grid"><div><span class="mm-kicker">Common questions</span><h2>Useful information before you begin</h2><p>Requirements vary by country and category. We consult with clients internationally to relate general requirements to individual circumstances.</p></div><div class="mm-accordion"><?php foreach ([['Can approval be guaranteed?', 'No. Decisions are made by the relevant immigration authority. We focus on clear, complete and consistent preparation.'],['What documents should I bring?', 'Bring your passport, travel history, education or employment details, financial information and any previous refusal letters.'],['Which destinations do you cover?', 'We assist with major destinations including the UK, Canada, Australia, New Zealand, the USA and selected European routes.'],['Can you review a refusal?', 'Yes. We can review the stated concerns and discuss possible next steps based on the available information.'],['Do you work with clients outside Lahore?', 'Yes. Phone and online consultations allow us to work with clients throughout Pakistan and internationally.'],['How do I book?', 'Call +92 321 167 1000 or email enquiries@mubeenmigration.com to arrange a discussion.']] as $i => $faq) : ?><details<?php echo 0 === $i ? ' open' : ''; ?>><summary><?php echo esc_html($faq[0]); ?></summary><p><?php echo esc_html($faq[1]); ?></p></details><?php endforeach; ?></div></div></section>
    <?php elseif ('privacy-policy' === $slug) : ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-prose"><h2>Your information and privacy</h2><p>We collect information you choose to provide when requesting a consultation or assistance. This may include contact details, identity information, education and employment history, travel history and supporting documents.</p><h3>How information is used</h3><p>Information is used to respond to enquiries, assess the requested service, prepare guidance and communicate about your matter. We do not sell personal information.</p><h3>Storage and sharing</h3><p>Reasonable measures are used to protect information. Details may be shared with service providers or authorities only where necessary for the requested service, required by law, or authorised by you.</p><h3>Your choices</h3><p>You may ask about the information held for you or request corrections by contacting <?php echo esc_html($email); ?>.</p><p><small>Last updated: <?php echo esc_html(wp_date('F Y')); ?>.</small></p></div></section>
    <?php else : ?>
        <section class="mm-inner-section"><div class="mm-wrap mm-content-grid"><article class="mm-main-copy"><figure class="mm-content-image"><?php mm_render_page_image('mm-page-feature-image', $title); ?></figure><span class="mm-kicker">A clear path forward</span><h2>Understand the route before you apply</h2><?php if (have_posts()) : while (have_posts()) : the_post(); ?><div class="mm-editor-content"><?php the_content(); ?></div><?php endwhile; endif; ?><p>Every application depends on individual facts, current rules and the quality of supporting evidence. Whether you are in Pakistan or overseas, our team can organise the process around your circumstances and intended destination.</p><div class="mm-check-grid"><div><b>01</b><h3>Initial assessment</h3><p>Clarify the destination, purpose, timing and relevant background.</p></div><div><b>02</b><h3>Evidence plan</h3><p>Identify the documents that support the route and your circumstances.</p></div><div><b>03</b><h3>Consistency review</h3><p>Check forms, dates, history and supporting information together.</p></div><div><b>04</b><h3>Final preparation</h3><p>Complete a structured readiness check before submission.</p></div></div></article><aside class="mm-side-card"><span>Need clear direction?</span><h2>Discuss <?php echo esc_html($title); ?></h2><p>Book a case-focused online or office consultation and bring your questions, history and available documents.</p><a class="mm-button" href="<?php echo esc_url($is_visa_page ? '#appointment-form' : home_url('/contact-us/#appointment-form')); ?>">Request an appointment</a><hr><b>Responsible guidance</b><small>No consultant can guarantee an immigration decision.</small></aside></div></section>
        <?php if ($is_visa_page) : ?>
            <section class="mm-inner-section mm-route-section"><div class="mm-wrap"><div class="mm-section-heading"><div><span class="mm-kicker">About this visa route</span><h2>What your preparation should cover</h2></div><p>Exact requirements vary by country, category and applicant. Current official rules must always be checked before submission.</p></div><div class="mm-route-grid"><article><span>Eligibility</span><h3>Purpose and route fit</h3><p>Confirm that the category matches your genuine purpose, planned duration and personal circumstances.</p></article><article><span>Evidence</span><h3>Documents that connect</h3><p>Prepare identity, financial, employment, education, family or sponsor evidence relevant to the route.</p></article><article><span>Application</span><h3>Accurate forms and history</h3><p>Keep dates, travel history, declarations and supporting documents complete and consistent.</p></article><article><span>Decision stage</span><h3>Next steps and timing</h3><p>Understand biometrics, possible requests for further information and the limits of published processing times.</p></article></div></div></section>
            <section class="mm-inner-section mm-visa-details"><div class="mm-wrap mm-detail-grid"><div><span class="mm-kicker">How we support you</span><h2>Case-focused guidance from enquiry to readiness</h2><p>Our team can review the proposed route, identify evidence gaps, structure a document plan and check the final application for avoidable inconsistencies. Consultations are available to clients internationally.</p><ul><li>Route and eligibility discussion</li><li>Personalised supporting-document checklist</li><li>Application and declaration consistency review</li><li>Previous refusal analysis where relevant</li><li>Preparation for submission and follow-up stages</li></ul></div><aside class="mm-contact-highlight"><span>Contact details</span><h3>Start your consultation</h3><a href="<?php echo esc_url($phone); ?>"><?php echo esc_html(MM_PHONE_DISPLAY); ?></a><a href="mailto:<?php echo esc_attr($email); ?>"><?php echo esc_html($email); ?></a><p>Online consultations worldwide<br>Office consultations in DHA Phase 5, Lahore</p></aside></div></section>
            <section class="mm-inner-section mm-form-section"><div class="mm-wrap mm-form-layout"><div><span class="mm-kicker">Appointment request</span><h2>Discuss <?php echo esc_html($title); ?></h2><p>Share your destination and circumstances. The form is emailed directly to our team for follow-up.</p></div><div><?php mm_render_appointment_form($title); ?></div></div></section>
        <?php endif; ?>
    <?php endif; ?>
</main>
<?php mm_site_footer($phone, $email); ?><a class="mm-mobile-call" href="<?php echo esc_url($phone); ?>">Call for consultation</a></div><?php wp_footer(); ?></body></html>
